# Training Configuration for RTX 5090 (32GB VRAM)
# Optimized for fast training without 4-bit quantization (bf16)

model:
  name: "meta-llama/Llama-3.1-8B"
  load_in_4bit: false
  bnb_4bit_compute_dtype: "bfloat16"
  bnb_4bit_use_double_quant: true
  bnb_4bit_quant_type: "nf4"
  device_map: "auto"
  trust_remote_code: true
  max_seq_length: 1024

lora:
  r: 16
  alpha: 32
  dropout: 0.05
  target_modules:
    - "q_proj"
    - "v_proj"
    - "k_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  bias: "none"
  task_type: "CAUSAL_LM"
  modules_to_save: []

training:
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  num_epochs: 3
  max_steps: -1
  learning_rate: 2.0e-4
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.03
  optimizer: "paged_adamw_8bit"
  weight_decay: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-8
  max_grad_norm: 1.0
  fp16: false
  bf16: true
  tf32: true
  gradient_checkpointing: false
  dataloader_num_workers: 4
  dataloader_pin_memory: true
  dataloader_prefetch_factor: 4
  evaluation_strategy: "steps"
  eval_steps: 200
  save_strategy: "steps"
  save_steps: 200
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "causal_stability"
  greater_is_better: true
  early_stopping_patience: 5
  early_stopping_threshold: 0.001
  logging_steps: 10
  logging_first_step: true
  report_to: ["none"]
  seed: 42
  data_seed: 42
  remove_unused_columns: false
  ddp_find_unused_parameters: false

loss:
  type: "causal_contrastive"
  lambda_task: 1.0
  lambda_causal: 0.5
  lambda_spurious: 0.5
  temperature: 0.07
  similarity_metric: "cosine"
  label_smoothing: 0.0

data:
  train_path: "data/processed/train_split.jsonl"
  val_path: "data/processed/val_split.jsonl"
  test_path: "data/processed/test_split.jsonl"
  max_length: 1024
  padding: "max_length"
  truncation: true
  use_cache: true
  cache_dir: "data/cache"
  min_length: 10
  max_samples: -1

checkpointing:
  output_dir: "checkpoints"
  resume_from_checkpoint: null
  save_safetensors: true

wandb:
  enabled: false
  project: "isef-causal-llm"
  entity: null
  name: null
  tags: ["llama", "lora", "causal-contrastive", "rtx5090", "isef"]

validation:
  compute_causal_metrics: true
  compute_attack_success_rate: true
  generate_samples: true
  num_samples_to_generate: 5
  generation_max_length: 256

advanced:
  attn_implementation: "sdpa"

hardware:
  gpu_name: "RTX 5090"
  vram_gb: 32
  cuda_device: 0
  empty_cache_steps: 50
  max_memory_allocated_gb: 30.0
  use_flash_attention: false
  use_triton: false
  compile_model: false

